[package]
name = "port-scanner"
version = "0.1.0"
authors = ["Ben Parli <ben.parli@creditkarma.com>"]
edition = "2018"
keywords = ["async", "network", "scan", "monitoring"]
categories = ["network-monitoring", "port-scanning"]

[dependencies]
futures = "0.3"
async-std = "1.5"
